spring.application.name=yallahemsi
server.port=8081

# --- Connexion m3a MySQL (Base de données khawya) ---
spring.datasource.url=jdbc:mysql://localhost:3306/Yallah_Emsi?serverTimezone=UTC
spring.datasource.username=root
# Khliha khawya ila knti khdam b XAMPP, wlla dir l'mot de passe dyalk
spring.datasource.password=123456789

# --- L'magie dyal Code-First (Creation automatique) ---
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect